### ISSUE TITLE
Twitter has close the v1.1 API to new users

### ISSUE THREAD

**Issue by jimerino** [Azure/azure-stream-analytics#106]
Hi,

Twitter has close the v1.1 API access to new users and the default version is the v2.0 API

All access to v1.1 API return a 403 Forbidden.

Is there any plan to migrate this sample to v2.0 API?

Regards,
Jose

**Comment by Fleid** [comment]
Hi @jimerino,
I'm sure we will update it at some point, but not in the near short term. You need to find an alternative tutorial/client that will send data from Twitter to Event Hub, all the following steps should line up.

**Comment by calmills** [comment]
Any further plans on this migration?

**Comment by Fleid** [comment]
Hi @calmills, no update here. We can help once the data is available in event hub, on how to best consume it with ASA. But how to export data from Twitter to event hub is out of scope at the moment. Sorry about that.
