### ISSUE TITLE
Stream Analytics Job getting failed while configuring the Power BI as a output. 

### ISSUE THREAD

**Issue by A-DavidJeyapaul** [Azure/azure-stream-analytics#118]
Hi Team,

We are trying to write the data from IoT hub to Power BI using Stream analytics job. We have tested the connection and its success. We have the static columns to be written into Power BI as per the below query. 

`
SELECT
DisplayName as Parameter,
Value.SourceTimestamp as Timestamp,
Value.Value as Value
INTO
[output-bi03]
FROM
[input-hub]`

When we start the job, its getting failed and its showing the error as **Send Events: Failed to send data to Power BI due to incompatible schemas.** But the Data sets and tables are created in the Power BI with no data. 

**Note: The Stream analytics Job is running on Dedicated Cluster.**

**Comment by Fleid** [comment]
Hi there, I'm wondering if that could be a type conversion error. Could you try to explicitly convert them by using either `TRY_CAST` (will output NULL if the conversion can't be done) or `CAST` (will crash the job if the conversion can't be done).

Also, do you have a sample input payload we could look at?

**Comment by A-DavidJeyapaul** [comment]
Hi @Fleid ,  Thanks for your quick response. I have updated the query like below. Its working fine. 
`SELECT
    DisplayName as Parameter,
    Value.SourceTimestamp as Timestamp,
    TRY_CAST(Value.Value AS bigint) as Value
INTO
    [output-bi03]
FROM
    [input-hub]` 

Does the job was getting failed due to the Conversion?
