### ISSUE TITLE
How can I execute unit test with GetMetadataPropertyValue calls

### ISSUE THREAD

**Issue by mjeannin2** [Azure/azure-stream-analytics#119]
context : 
I want to test an ASA job using GetMetadataPropertyValue for getting IOTHUB additional properties configured in routing.
This device metadata are used in the ASA job as conditions 
(eg where (result of GetMetadataPropertyValue function) = "condition")

Question : 
When I create a unit test I didn't found a way to add this additional datas to the unit test input file

Thanks for your help
Maxime

**Comment by Fleid** [comment]
Hi there, 

You can simply add the required field in a "user" top level record of your sample files.
If you need `GetMetadataPropertyValue(myInput,"[User].[myCustomProp]")`, you can add the following field to your input file:

```JSON
{
   ...,
   "User":{
      "myCustomProp" : "myValue"
   }
}
```
