### ISSUE TITLE
Composite path using concatenated columns does not generate folders correctly

### ISSUE THREAD

**Issue by LouisSkyline** [Azure/azure-stream-analytics#120]
Since 18/04/2022 at around 18u30 utc our stream analytics jobs do not create the folder structure correctly anymore.

We use a composite column as described in the documentation [here](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-custom-path-patterns-blob-storage-output#limitations).
Like this: pathPrefix/{PathUrl} where PathUrl is from the format "year=2022/month=04/day=18"

But instead of creating 'pathPrefix/year=2022/month=04/day=18/' folders. The job creates folders of the format pathPrefix/year%3D2022%2Fmonth%3D04%2Fday%3D18/.

**Comment by sidramadoss** [comment]
@LouisSkyline - sorry to hear this is happening. If you happen to have a support ticket associated for this, could you please email askasa@microsoft.com? If you don't have a support ticket, please share via email the resource id and region.
