### ISSUE TITLE
setup.exe fails when already installed from other location

### ISSUE THREAD

**Issue by vykhand** [Azure/azure-stream-analytics#17]
Hi there! It would be nice to have an instruction or a fix that allows to run the application from a new location each time. If you start this app from one place on disk, it would not allow you to start it from any other place anymore.

**Comment by jeffstokes72** [comment]
Hello, which setup.exe are you referencing please?

**Comment by vykhand** [comment]
Hi! I am talking about labs5 and 6 from aka.ms/aalab, and TelcoGenerator application:
![image](https://cloud.githubusercontent.com/assets/498481/23232524/ceb5ba0c-f94b-11e6-9844-ff647c356966.png)

**Comment by jeffstokes72** [comment]
This appears to be a compiled binary of our sample code. I note the http://aka.ms/aalab is downloading from a storage blob in EMEA. The documents in the zip appear to be centered around a MTC engagement. Are you participating in that and they directed you to download this zip? It isn't actually ours, we don't provide a compiled copy in our repo here.

**Comment by Fleid** [comment]
Closing stale issues
