### ISSUE TITLE
TollApp project setup.ps1 fails

### ISSUE THREAD

**Issue by ChadHattabaugh** [Azure/azure-stream-analytics#25]
When running setup.ps1 contained in the Tollbooth project, the script fails to create the event hub with the following error: 

Exception calling "CreateEventHubIfNotExists" with "1" argument(s): "The remote server returned an error: (400) Bad
Request. SubCode=40000. **EventHub can't be created in a messaging namespace after '4/5/2017 12:00:00 AM +00:00' utc.
Please create it in EventHub namespace.**

**Comment by Fleid** [comment]
Closing stale issues
