### ISSUE TITLE
Different Output into Data Lake Store that depend on device id (iot hub input)

### ISSUE THREAD

**Issue by dawcza3** [Azure/azure-stream-analytics#26]
Is there any way to set an output path prefix in Stream Analytics job that store data to Data Lake Store to store it into separate files (that dependent on device id) for example data/2017/5/3/device1.csv , data/2017/5/3/device2.csv ... Or what is the best way to do this after stream analytics store data to one file ? My input file is iot hub.

**Comment by nielsvn92** [comment]
I would very much like this feature to be implemented. It makes it way easier to process / query the masses of data.

**Comment by Fleid** [comment]
Closing stale issues
