### ISSUE TITLE
CosmosDB with TableApi as output not working

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-stream-analytics#27]
Hi, I have the solution with IoT Hub as events source, stream analytitcs and CosmosDB with Table API as storage. 
The messages from IoT Hub are like this
```javascript
     {"id":56,"deviceId":"test2","cloudTagId":"cloudTag1","value":27.968841118384056}
```
The query is following:
```sql
SELECT 
    concat(deviceId, cloudtagId) as telemetryid, value as temperature, id, deviceId, 'asd' as '$pk', deviceid as PartitionKey
INTO
    [TableApiCosmosDb]
From
    [devicesMessages]
```
I have added '$pk' alias because previously I have gotten error `The output record does not contain the column '$pk' to use as the partition key property by DocumentDB`
But even after I added that column to output I aslo constantly get that error.
Is there any workarounds or am I doing smth wrong?

**Comment by Fleid** [comment]
Closing stale issues
