### ISSUE TITLE
UDF returning datetime throws error

### ISSUE THREAD

**Issue by pelocruz** [Azure/azure-stream-analytics#29]
Hi,

I am having some issues implementing a Javascript user defined function that returns a datetime object. I have done a simplified test where:
- Input: Data stream from IOTHub.
- Output: Blob storage.
- Query:
```
SELECT *, udf.parseDateTime(1) AS [UDFTimestamp]
INTO [Output]
FROM [Input]
```
- UDF: Output Type: datetime
```
function main(arg1) {
    return new Date(2017,1,2,3,4,5);
}
```

The moment the job receives a message, the job stops with the following error:
```
    "properties": {
        "Message Time": "2017-06-30 06:23:49Z",
        "Error": "- Specified cast is not valid.\r\n",
        "Message": "Runtime exception occurred while processing events, - Specified cast is not valid.\r\n, : OutputSourceAlias:output;",
        "Type": "SqlRuntimeError"
    }
```

Changing the Output Type of the UDF to "any" returns an empty object.

Does anyone have any insights on what could be wrong?

**Comment by farrukh-normuradov** [comment]
I face the same issue when I use PowerBI. 

Is it a bug or configuration issue?

**Comment by Fleid** [comment]
Closing stale issues
