### ISSUE TITLE
Switch-AzureMode is deprecated

### ISSUE THREAD

**Issue by GitHubUser1339** [Azure/azure-stream-analytics#3]
The POSH script uses the deprecated switch-azuremode cmdlet and doesn't work anymore with the new POSH cmdlets for Azure.

https://github.com/Azure/azure-powershell/wiki/Deprecation-of-Switch-AzureMode-in-Azure-PowerShell

**Comment by deldersveld** [comment]
I went through the setup.ps1 file this morning and updated to AzureRm cmdlets where appropriate. I have not submitted a PR because it still requires two separate logins for ASM and ARM, but I at least have a working copy in my fork.

**Comment by Fleid** [comment]
Closing stale issues
