### ISSUE TITLE
Azure stream analytics doesn't list custom endpoints in IoT Hub Source Input

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-stream-analytics#30]
Hi,

I have an IoT Hub with custom endpoints which sink data into service bus queues. Since i implemented custom routing through custom endpoints in IoT Hub & Service bus queues. When i try to create Azure Stream Analytics (ASA) job, the input panel in azure portal does not list custom endpoints but only consumer groups which work only for default messaging endpoint. Is there a way to let ASA to pick messages off service bus queues or custom endpoints in IoT Hub? So i do not need to modify custom routing i already have.

I want to be able to copy these messages from service bus queues using ASA into a storage account. That's the reason i am using custom routes that redirects messages into service hub queues.

Thanks and looking forward to your thoughts.

**Comment by Fleid** [comment]
Closing stale issues
