### ISSUE TITLE
Query: named field output as lowercase

### ISSUE THREAD

**Issue by ApiO** [Azure/azure-stream-analytics#34]
Hi,

Using the portal, I have a stream analytics query that make a simple select fom an input stream and output it to an Azure Service Bus topic. Nothing fancy.

If I name my field in the query the service bus recieve the properties name in lowercase, if I use SELECT * everything works fine.

Input data format:

> {"deviceId":"0123654789658741236595148", "foo":"bar","fu":"sroda"}
 

If the query is:
> SELECT deviceId INTO OutputStream FROM InputStream 

The bus message contains a string with "device**id**"

If the query is:
> SELECT * INTO OutputStream FROM InputStream 

The bus message contains a string with "device**Id**"

It's quiet surprising !

**Comment by FabriceMk** [comment]
It's a bug that confuse people, it forced us to delete our CosmosDB collection and recreate it with a lowercase partition key (where we already migrated some data, it forced us to re-migrate).

**Comment by ApiO** [comment]
Damn this one still exists!

**Comment by sebader** [comment]
This is available by now when changing the compatability mode to 1.1: https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-compatibility-level 

> current version: case-sensitivity is persisted for field names when they are processed by the Azure Stream Analytics engine.

**Comment by JSeb225** [comment]
Closing issue since we have a fix as mentioned by @sebader
