### ISSUE TITLE
Please add support for "early" events when using event ordering

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-stream-analytics#36]
If you look under the event ordering tab in ASA, it allows for you to support events that arrive late, this is great but it sacrifices latency to do this.  For every minute I want to tolerate late events I must tolerate that minute in latency instead.  Instead allow me to get "early" events that arrive before my late window is over.  It could even have some header or signifier that this calculation is subject to change based on your late window.  This would give me the best of both worlds.  I could take immediate action based on the information I have at hand but then also if events arrive late and I get new calculation then I could get a second event with the more correct data.  This could even have multiple events happen thoughout the late window assuming multiple late data events arrived.  Of course there would need to be some configuration.  You might not want a new aggegrate event to be spit out everytime a new late input came in.  Some threshold change or time delay should be good enough.  But at least in the simplest case 1 event immediately with the information that is on hand and a 2nd event at the end of the late window with more accurate information would be great.

**Comment by AceHack** [comment]
Actually what might be even better is to just let me configure the event ordering on each of the outputs individually instead of the ASA as a whole.  That way I could have different outputs that tolerate different levels of late events and latency as desired.

**Comment by AceHack** [comment]
Actually I'm not sure it's "better" to let me configure event ordering on each output than the ability to get "early" events.  I could see both useful in the case where "early" events can report more than one "early" event and send multiple updates as the data changes when it arrives late.

**Comment by Fleid** [comment]
Closing stale issues
