### ISSUE TITLE
Deploy Stream Analytics Job for IoT Edge

### ISSUE THREAD

**Issue by MaxiPigna** [Azure/azure-stream-analytics#39]
I think is missing a way to automatically deploy a Stream Analytics Job having **Edge** as **Hosted Environment**.
I couldn't find anything to create it by using an [ARM template](https://docs.microsoft.com/en-us/azure/templates/microsoft.streamanalytics/streamingjobs), [Powershell](https://docs.microsoft.com/en-us/powershell/module/azurerm.streamanalytics/New-AzureRmStreamAnalyticsJob?view=azurermps-5.4.0) or Azure CLI.

**Comment by hubez** [comment]
I am really interested in this too. Looking for an end-to-end example of just CLI commands to create and then subsequently update ASA Edge jobs, and Edge deployments to use as a basis for CI/CD infrastructure.

**Comment by Fleid** [comment]
Closing stale issues
