### ISSUE TITLE
Problem with "Input string was not in a correct format."

### ISSUE THREAD

**Issue by rationalizer** [Azure/azure-stream-analytics#40]
I'm following instructions here: https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-real-time-fraud-detection

However, when I type "telcodatagen.exe 1000 .2 2" in command prompt I get the following error:

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at telcodatagen.Program.GenerateData(String[] args) in C:\WORK\Enlist\GitHub\azure-stream-analytics\DataGenerators\TelcoGenerator\Program.cs:line 86
   at telcodatagen.Program.Main(String[] args) in C:\WORK\Enlist\GitHub\azure-stream-analytics\DataGenerators\TelcoGenerator\Program.cs:line 55

My telcodatagen.exe.config looks like this:
`<appSettings>
    
    <add key="EventHubName" value="sa-eh-frauddetection-demo"/>
    <add key="Microsoft.ServiceBus.ConnectionString" value="Endpoint=sb://jm-eh-ns-demo.servicebus.windows.net/;SharedAccessKeyName=sa-policy-manage-demo;SharedAccessKey=e+b0gErV9Exmnw/JuH8FTh9UzVa6Vw2...Uosg="/>
  </appSettings>`

I added the dots to the key. Please advice.

**Comment by NilsFlaschel** [comment]
Same Problem here, is there a solution to this?

**Comment by Kuandyk789** [comment]
I tried changing the point (0.2) to a comma (0,2) and it worked :D

![image](https://user-images.githubusercontent.com/56952774/67460694-7c575380-f65d-11e9-95ea-4e1f3684141a.png)

**Comment by Fleid** [comment]
Closing stale issues
