### ISSUE TITLE
Send Data to Cosmos DB created with MongoDB API fails.

### ISSUE THREAD

**Issue by surabhshah** [Azure/azure-stream-analytics#41]
Hello,

We were recently trying to pass on the data from IoT hub on to the Cosmos DB which is based on MongoDB API using Stream Analytics Job, keeping the default query with input and output aliases. However, the data is not inserted into the DB even if a collection is already present. We are not getting any errors on Stream Analytics part, however, Cosmos DB does not contain any documents and shows an error as below.

> Detected corrupted documents without _id identifier, verify that you are only storing documents through Mongo protocol and not SQL API or DocumentDB SDK

We could see the input and output events in metrics and hence infer that the data was received by streaming job.

Any help regarding the same is appreciated.
Thanks in Advance!

Regards,
Surabh

**Comment by krunallokhande** [comment]
Same issue..

**Comment by sidramadoss** [comment]
ASA only supports connection to CosmosDB using SQL API. Other Azure Cosmos DB APIs are not yet supported. We have plans of supporting other APIs like MongoDB in our roadmap.

**Comment by Fleid** [comment]
Closing stale issues
