### ISSUE TITLE
Full Azure solution for Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by marcusvcs** [Azure/azure-stream-analytics#42]
Hi,

I found this project via this tutorial (https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-twitter-sentiment-analysis-trends) and I was wondering if the TwitterClient application could be converted or reimplemented using an Azure service, like a Batch service, for example.

My idea is to run the entire solution on the cloud, with no need to keep this application running on a local machine to receive tweets.

Can anyone give any tips about that?

**Comment by martinezpedro** [comment]
try spark hdi or azure databricks.

**Comment by Fleid** [comment]
Closing stale issues
