### ISSUE TITLE
Creating ASA on edge -  'streamingUnits' is null 

### ISSUE THREAD

**Issue by falloutxAY** [Azure/azure-stream-analytics#45]
When creating a Streaming analytics job for Edge deployment, there is an error which is 

> The value of deployment parameter 'streamingUnits' is null. Please specify the value or use the parameter reference. See https://aka.ms/arm-deploy/#parameter-file for details. (Code: InvalidDeploymentParameterValue)

Work around is to select Cloud first, key in the number of streamingUnits before changing the selection to Edge.

**Comment by mamccrea** [comment]
Thank you for the feedback! We are looking into this issue - can you please provide some additional information?

- URL used to create the job
- Location region
- Does it happen every time, or is the issue intermittent?
- Please upload a screenshot

**Comment by shizn** [comment]
same issue here

- URL used to create the job
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics

- Location region
every region

- Does it happen every time, or is the issue intermittent?
yes

- Please upload a screenshot
if you follow the instruction exactly, you will see the error.


Thanks @falloutxAY  for the workaround.

**Comment by JasonWHowell** [comment]
@JSeb225 Do we have a bug to track this already? making Streaming Units box in the portal unnecessary for IoT Edge jobs.

**Comment by mamccrea** [comment]
A fix related to this was made today.
