### ISSUE TITLE
No events reported and Avro Codec Null error is thrown

### ISSUE THREAD

**Issue by michaelnemtsev** [Azure/azure-stream-analytics#46]
I followed the configuration steps as described there https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/stream-analytics/stream-analytics-twitter-sentiment-analysis-trends.md 

However, the tool doesn't capture any Twitter events. I enabled the event capture to blog and I see the following messages

> Objavro.codecnullavro.schemaì{"type":"record","name":"EventData","namespace":"Microsoft.ServiceBus.Messaging","fields":[{"name":"SequenceNumber","type":"long"},{"name":"Offset","type":"string"},{"name":"EnqueuedTimeUtc","type":"string"},{"name":"SystemProperties","type":{"type":"map","values":["long","double","string","bytes"]}},{"name":"Properties","type":{"type":"map","values":["long","double","string","bytes","null"]}},{"name":"Body","type":["null","bytes"]}]} öû\Ü$&£D°èc5éó  öû\Ü$&£D°èc5éó

What could be the issue?

**Comment by michaelnemtsev** [comment]
ok the issue turned out to be using an old MessageBus lib. Just get the source code and upgrade the MessageBus NuGet package to the latest one

**Comment by tribhuwann** [comment]
I am very new with visual studio and azure portal. could you please let me know the steps to upgrade the code.

**Comment by tribhuwann** [comment]
![image](https://user-images.githubusercontent.com/32473347/45007899-db778600-afcd-11e8-9acf-c6b364a4a7ce.png)

**Comment by michaelnemtsev** [comment]
@tribhuwann - check here https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui and upgrade the existing nuget packages to the latest versions
