### ISSUE TITLE
How to change the sentiment to spanish?

### ISSUE THREAD

**Issue by martinezpedro** [Azure/azure-stream-analytics#47]
Currently works detecting sentiment with English keywords, how can I make the application work with spanish?

**Comment by JSeb225** [comment]
Sorry for the delayed response. We are using Sentiment140 which supports both English and Spanish (more info [here](http://help.sentiment140.com/api)). This will require to modify the client app calling this API in this [source file](https://github.com/Azure/azure-stream-analytics/blob/master/Samples/TwitterClient/TwitterClient.Common/Entities/Sentiment140.cs). In the future we can change the code to "auto" so it works for both English and Spanish.
