### ISSUE TITLE
Error at reading connection string.

### ISSUE THREAD

**Issue by marcosroriz** [Azure/azure-stream-analytics#5]
I've followed the tutorial on: https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-get-started/

But I'm getting the following error:
Unhandled Exception: System.FormatException: Input string was not in a correct format.at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt) at System.Single.Parse(String s) at telcodatagen.Program.GenerateData(String[] args) in C:\WORK\Enlist\GitHub\azure-stream-analytics\DataGenerators\TelcoGenerator\Program.cs:line 86 at telcodatagen.Program.Main(String[] args) in C:\WORK\Enlist\GitHub\azure-stream-analytics\DataGenerators\TelcoGenerator\Program.cs:line 55

My hubname is: hubhello
My connection key is: Endpoint=sb://hubhello-ns.servicebus.windows.net/;SharedAccessKeyName=TestAPI;SharedAccessKey=mykey=

**Comment by jeffstokes72** [comment]
Remove the sharedaccessname from the endpoint entry.

Replace the EventHubConnectionString and EventHubName values in TwitterClient.exe.config with your Event Hub connection string and name. The connection string you copied earlier gives you both the Event hub connection string and the name, so be aware to separate them and put each in the correct field.
