### ISSUE TITLE
How to Compressing and optimizing Azure IoT Message using C code

### ISSUE THREAD

**Issue by ampac28** [Azure/azure-stream-analytics#52]
We are using IoT SDK in C language to send Device telemetry data to IoT hub. Now to reduce cost we are planning to use GZip at Stream analytics side and want to send compress data to IoT using C code. 

When we followed one sample article which is in Python , it worked for us but when we tried same with using C code , it is not working. 

Please let me know if you need our C code to share .

Regards,
Amit Pachahara

**Comment by JSeb225** [comment]
Hi, sorry to hear you have some issues.  Do you see an error in Azure Stream Analytics, or do you have an error when you compile or run the C code? Can you share more info about the error?

**Comment by Fleid** [comment]
Closing stale issues
