### ISSUE TITLE
Error Occurred at set functions to output

### ISSUE THREAD

**Issue by YuichiNukiyama** [Azure/azure-stream-analytics#53]
## Description
After setting functions to output, delete it. After that, an error occurs when resetting. Probably, I think that old keys are automatically acquired.

## Reproduce steps
1. create Stream Analytics
1. create Functions
1. set Functions to output
1. delete output
1. delete Functions
1. re-create functions
1. set Functions to output, again (error occurrs)

## Expected behavior
Set functions to output successfully.

## Real behavior
Error occured (See below).

![func](https://user-images.githubusercontent.com/9623009/49583044-40aa9100-f99a-11e8-877c-0d69d8523c92.PNG)

![error](https://user-images.githubusercontent.com/9623009/49583048-456f4500-f99a-11e8-97d6-a6e701ca09be.PNG)

**Comment by Russellmd** [comment]
I have almost the same problem, even if I deleted and created again all resources (Iot Hub, Stream Analytics, Function App, etc.)

In my case Key field is every time empty and Save button is disabled, even if in documentation is mentioned that for current subscription Key is an optional value
![Screenshot from 2020-01-23 17-01-55](https://user-images.githubusercontent.com/6410931/73001142-46637000-3e02-11ea-83c6-6777980bb027.png)

**Comment by sidramadoss** [comment]
@Russellmd and @YuichiNukiyama - sorry for the late reply. were you able to overcome this problem? if not, can you please email details of your job and function to askasa at microsoft dot com?

**Comment by Fleid** [comment]
Closing stale issues
