### ISSUE TITLE
Error when deploying Stream Analytics job containing tabs with "Azure Resource Group Deployment" task 

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-stream-analytics#54]
I also added this issue in the "azure-resource-manager-schemas" section because I wasn't sure what the best location should be.

When you deploy a Stream Analytics job with an "Azure Resource Group Deployment" task with a query that contains tab characters, the deployment task results in a failure.

**Comment by JSeb225** [comment]
Hi @Joehannus, sorry for the delayed response.
We tried to deploy a job with a query containing a tab character and it works. Can you share more info either here, or by email at askASA@microsoft.com 
If you can share the job definition you were trying to deploy, and the error message you saw, that will be useful.
