### ISSUE TITLE
Stream Analytics Query/Output 

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-stream-analytics#6]
This is the first error:

`WARNING 05/19/2016 15:46:14
Error encountered while trying to convert the event to the Azure table entity:
Storage account: [{{dbName}}] table: [{{tableName}}] - Expected property named: PartionKey used for:
PartitionKey is not found in output record.
Please check if the property name is configured and all Correctly if the output events has a property called PartionKey`

[Fixing the warning](https://github.com/mauricionr/TwitterClient/blob/master/TwitterClient/Program.cs#L32)

After fix the error above i'm getting this error

`WARNING    19/05/2016 18:36:27 Additional details are temporarily unavailable.`

I'm sending data from twitter to an event hub and i'm trying first populate my storage table and then i will make some query to analyse some particular data.

Here's my repo that send data to Azure Event Hub

[Sending data](https://github.com/mauricionr/TwitterClient/blob/master/TwitterClient/EventHubObserver.cs#L49)

Here's my sample query

`SELECT *
INTO [output2posts]
FROM [stream-event-hub]`

Any ideia?

Thanks

**Comment by of-rupesh** [comment]
Is this issue still open? This issue usually occurs if your event-hub/IoT-hub is receiving multiple inputs of different format (or Different JSON inputs). 
The query you set on stream Analytics expects the Partition key and row key defined by you and expects it in the JSON input you IoT/Event hub is receiving.
