### ISSUE TITLE
Service bus topic output to array results in singleton json object

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-stream-analytics#60]
I implemented a stream analytics job that outputs its data among others to a service bus topic. The chosen output format is Array.

However when checking the contents in the subscriptions each received message contains one singleton json object, in stead of a json array containing one singleton json object.

**Comment by chetanmsft** [comment]
This is a known issue, Format doesn't apply to Service Bus outputs and will be deprecated for those in future. Format (Line separated/Array) is applicable for multiple events per message (like in Event Hub output). However Service Bus outputs only send one event per message, so separating events format is not applicable to them.

**Comment by Fleid** [comment]
Closing stale issues
