### ISSUE TITLE
"NotFound" / "BadRequest" error when deploying Stream Analytics with invalid name via ARM template

### ISSUE THREAD

**Issue by sguisu** [Azure/azure-stream-analytics#61]
When trying to deploy a new Stream Analytics job via Resource Group Deployments I am getting the following error, if the name of the job has an invalid format (e.g. non-alphanumeric, or dots in the string).
```
"statusCode": "NotFound",
      "statusMessage": {
        "error": {
          "code": "BadRequest",
          "message": ""
        }
      }
```
Changing the resource name from
`"resourceName": "Domain.Example.Artifact"`
to
`"resourceName": "Domain-Example-Artifact"`
makes the trick and the deployment works.

The ARM template is in fact validated with no problems, so it is not possible to identify the error with this description. **It would be great if a more descriptive message is enclosed in the error output.** 

In Azure Portal a validation in the correspondent input field is included, so this error does not happen.

**Comment by sidramadoss** [comment]
Thanks for the feedback @sguisu . We will fix this.

**Comment by ThomasPe** [comment]
@sguisu Oh god - thanks for sharing! This would have probably cost me days. I owe you a beer!
