### ISSUE TITLE
From Iot Hub to Blob Storage Problem

### ISSUE THREAD

**Issue by Ilheu** [Azure/azure-stream-analytics#62]
Hi, I configured a job just to storage the messages I received from Iot Hub to a blob Storage, but it isn't working ... Can someone help me find what is wrong ? 

My input : 
![input](https://user-images.githubusercontent.com/8053606/54364488-e853f100-4664-11e9-920a-bca33377cffb.JPG)

My output: 
![image](https://user-images.githubusercontent.com/8053606/54364461-df631f80-4664-11e9-8c66-e844dbf03cfe.png)

The overview:

![image](https://user-images.githubusercontent.com/8053606/54364153-33213900-4664-11e9-9e93-ce8a6ce9dc4b.png)

**Comment by sidramadoss** [comment]
Looks like your job isnt receiving inputs from the IoT Hub. You can try troubleshooting by following the steps here: https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-troubleshoot-input#input-events-not-received-by-job
