### ISSUE TITLE
Query Twin Device tags in Stream Analytics

### ISSUE THREAD

**Issue by Ilheu** [Azure/azure-stream-analytics#63]
Is it possible to use twin device information in my Stream analytics queries ?

**Comment by StreamingTodd** [comment]
What device twin information are you interested in? This is not supported currently. The preferred method is to take a snapshot of your device twin data and then use it as reference data.

**Comment by Ilheu** [comment]
How can I take that snapshot ? I'm trying to use nodejs to that, but I had not success ...

**Comment by omki12** [comment]
even if "device twin" is not supported, "device twin tag" is supported. 
so basically what u can do is, use "Message Enrichment" to add your "device twin property" to "device twin tag property", and can use this in stream analytics. 

ref links: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-message-enrichments-overview

so msg flow will be : Message -> Enrich message = (Message + twin.tag) -> Stream analytics
