### ISSUE TITLE
Stream Analytics UDF works in Test but not in Job

### ISSUE THREAD

**Issue by wickkiey** [Azure/azure-stream-analytics#67]
I need to parse a JSON data in Stream Analytics, 

Below is the sample is am using,

    SELECT
         UDF.parseData(GetRecordPropertyValue(GetArrayElement(A.message,0), 'raw')).intent as 'rawData'
    FROM
        AppInsightMessages A  

I can able to parse the intent from the field. This is a custom logging required. 

However it is not working in Stream analytics job. 

I am getting error like

    Stream Analytics job has validation errors: Query compilation error: Expression is not supported: 'udf . parseData 

Tried with `CAST` ing to string to record also. no luck.

What I am doing wrong  ? 
thanks in advance ..

**Comment by jernelson7** [comment]
I have the same issue

**Comment by Fisher-Joe** [comment]
same.

**Comment by sidramadoss** [comment]
can you try parsing the json object in the udf to retrieve the specific fields you're interested in and return that (instead of the json record itself)? This will prevent you from having to do udf.foo(param).elementName.

**Comment by sidramadoss** [comment]
This seems to be a bug in Stream Analytics and we will work on addressing this asap. In the meantime, you can try select "compatibility level" on the portal and choose 1.2 as a temporary workaround.
