### ISSUE TITLE
Stream Analytics "Timestamp By ApplicationTime Over" is "over" partitioning

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-stream-analytics#70]
I recently changed a Stream Analytics job by adding an "Over" statement to a "Timestamp By" application time statement. A bit of background - our data contain a MeasurementTime, an AssetId and a DataPointId field. The new Timestamp By statement is as follows:

FROM IotEvents i TIMESTAMP BY MeasurementTime Over AssetId, PartitionId
PARTITION BY PartitionId.

(Before it was was "FROM IotEvents i TIMESTAMP BY MeasurementTime")

The data are among others processed in a tumbling window of 1 hour (in which an average is calculated for each datapointid). The output of that window is outputted to an event hub output, for which partitioning has also been set to "AssetId".

On the event hub in question we have an Event Hub Triggered Azure Function which processes the data that is sent to this Event Hub.

Before we added the Over statement all Data points for a specific asset and for a specific hour were received together in a single array in the azure function mentioned before.

After we added the Over statement each data point is received separately for a specific asset and for a specific hour by that Azure Function.

For instance - we have an asset with 10 data points. Before the change we only got one message with an array with 10 records (one for each data point). After the change we got 10 separate message on the function, each containing a record for one of the data points.

I would have expected that the behavior would have stayed the same. We really need the complete list of Data points for a specific asset for further processing.

I quote the documentation:
"Example 4 – Handling multiple timelines in a partitioned query
Process data from different senders (toll stations) without applying time policies across different toll station IDs. The input data is partitioned based on TollId."

(https://docs.microsoft.com/en-us/stream-analytics-query/timestamp-by-azure-stream-analytics)

**Comment by Phil4Code** [comment]
Hi Joehannus,

I had the same issue, but you can solve it by applying the 'Partition By' directly on the window itself.

See the paragraph SESSION WINDOW, I suspect it works with other window types, too: 
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/stream-analytics/stream-analytics-stream-analytics-query-patterns.md
