### ISSUE TITLE
Issue running this App

### ISSUE THREAD

**Issue by pemar-MSFT** [Azure/azure-stream-analytics#73]
Hello. I am unable to run [this App](https://aka.ms/azure-stream-analytics-telcogenerator), as I get the following error:
![image](https://user-images.githubusercontent.com/58558936/70240596-69a86200-1765-11ea-9166-94d01922fcc7.png)
This issue appeared on [this step of the Azure tutorial](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-real-time-fraud-detection#start-the-app).

Feel free to ping me for details as I'm internal. Cheers.

**Comment by sidramadoss** [comment]
hi @pemar-MSFT , when you copy the connection string from the Event Hub SAS policy and paste this to the config file of the telcogenerator, please make sure the 'EntityPath' part of the connection string is removed. When you copy the connection string, it will be of the form:
"Endpoint=sb://abc.servicebus.windows.net/;SharedAccessKeyName=name1;SharedAccessKey=<id>;EntityPath=name"

In the above example, you would have to remove the last part ";EntityPath=name".

**Comment by ahalabi** [comment]
This app does not work, When I click on the green button nothing happens. any idea if this actually works. 
https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-twitter-sentiment-analysis-trends#configure-the-client-application

tnx
