### ISSUE TITLE
events not delivered to eventhub output 

### ISSUE THREAD

**Issue by mjeannin2** [Azure/azure-stream-analytics#79]
Context : 
We use stream analytics with IotHub a input and eventHub as output with many messages as input.
Stream analytic job is configured to be fully parallel with "partition by" query.
Stream analytics is configured with 12 SU

Problem : 
Stream analytics encountered an error and is not able to continue to deliver data :

"operationName": "Send Events", "category": "Execution", "status": "Failed", "level": "Warning", "properties": "{\"Error\":\"- An error occurred while sending data to Event Hub.  The following information could be helpful in diagnosing the EventHub issue: [EHO MultiSender [Endpoint=.../;TransportType=Amqp;\\/streama-to-tempsreel], PartitionId: [0, 1, 2], Key [ ]] - failed to flush events. Object reference not set to an instance of an object.  System.NullReferenceException: Object reference not set to an instance of an object.\\r\\n- Object reference not set to an instance of an object.\\r\\n\",\"Message\":\"Output is currently experiencing transient errors. Retrying...\",\"Type\":\"OutputProcessorTransientError\",\"Correlation ID\":\"0d4e1623-c484-4a4d-a8b7-3ef0d7410967\"}"} 

expected result : 
messages are sent to event hub

**Comment by sidramadoss** [comment]
This is a transient error which ASA will automatically recover. Are you still facing this problem?
