### ISSUE TITLE
Output stream creates infinite blob files when immutability policy is enabled on storage account

### ISSUE THREAD

**Issue by domedellolio** [Azure/azure-stream-analytics#81]
Hi team,

I have created a multi-tenant audit solution using Event Hub combined with stream analytics. that store logs into a storage account.
Everything works well and as expected when immutable policies are off on target storage account.
If enabled instead, Stream Analytics job creates infinite files on cointainers.

Query I'm using:

`WITH   
AllEvents AS  
(  
  SELECT 
       [User]
      ,[Timestamp]
      ,[TenantGroup]
      ,[TenantId]
      ,[EntityName]
      ,[EntityId]
      ,[EntityCode]
      ,[EntityAction]
      ,[Changes]
	  ,[ContextInfo]
      ,[Ttl]
  FROM [eusoft-evh-glo01-audit-prd] TIMESTAMP BY [Timestamp]
),  
GR001 AS  
(  
  SELECT *  
  FROM AllEvents  
  WHERE tenantGroup='gr001'  
),  
GR002 AS  
(  
  SELECT *  
  FROM AllEvents  
  WHERE tenantGroup='gr002'  
)

SELECT * INTO [eusoft-st-glo01-audit-prd] FROM AllEvents /** <-- Storage account **/
SELECT * INTO [eusoft-sqldb-gr001-audit-prd] FROM GR001 /**<-- SQL **/
SELECT * INTO [eusoft-sqldb-gr002-audit-prd] FROM GR002 /**<-- SQL **/

`

**Comment by Fleid** [comment]
ASA doesn't support immutable blob as output. An error message was added mid 2020 to prevent users from creating an output on one.
