### ISSUE TITLE
Blobstorage output API calls - how to reduce number of calls ?

### ISSUE THREAD

**Issue by mjeannin2** [Azure/azure-stream-analytics#82]
Hello team,

We configured a Stream analytics with Blobstorage as output. The blob storage API calls increase a lot.
The number of calls of API putBlock increase to 100x
We tried to reduce number of calls to this API by increasing number of "minimum rows" and "maximum time" parameters (in ASA output configuration) without any result.
Is there a way to increase blocks size or other to reduce the number of API calls.

Many thanks

**Comment by an-emma** [comment]
By increasing the minimum rows, the number of API calls should be reduced. How do you measure the number of API calls, and what is the number you set the minimum rows to? We will wait for a batch to fill up to the number of min events before calling blob API.
