### ISSUE TITLE
Connection test failed : 401 Unauthorized for calling function app

### ISSUE THREAD

**Issue by ApoorvaPetkar** [Azure/azure-stream-analytics#85]
When trying to test function app output in stream Analyzer, how to provide authentication for function app from Stream Analyzer. I have already provided key value in the Output details configuration. Please let me know the procedure to get authenticated for Function app in SA.

getting following error:
Could not successfully send an empty batch to the Azure Function. Please make sure your function app name, function name, and API key are correct and that your Azure Function compiles. If all of those parameters are correct, Azure Functions may be temporarily unavailable at this time. Please try again later.  Azure Functions returned with response code of 401: Unauthorized. It should respond with a 200, 202, or 204.

**Comment by surabhshah** [comment]
Hi Apoorva,

Please could you confirm that the authentication mechanism expected by Azure Function is 'Function Key' and the same is configured while creating the output.

Regards,
Surabh Shah

**Comment by mariuszdybala** [comment]
Do have any update regarding this issue? I've encountered the same problem.
My settings:

- Function app setup => Authentication(classic) => "Action to take when request is not authenticated" => set to "Log in with Azure Active Directory"
- Function app setup =>Function Authentication mode is set to AuthorizationLevel.Function

- Stream analytics output setup => Azure Function output configurated with all possible keys (app keys and function keys) => all attempts failed with 401 status 

The thing is, once I set Authentication(classic) => "Action to take when the request is not authenticated" => set to "Allow anonymous request (no action) then the Stream analytics could test connection successfully.

Here is the message that I receive:

"Could not successfully send an empty batch to the Azure Function. Please make sure your function app name, function name, and API key are correct and that your Azure Function compiles. If all of those parameters are correct, Azure Functions may be temporarily unavailable at this time. Please try again later.  Azure Functions returned with response code of 401: Unauthorized. It should respond with a 200, 202, or 204."

**Comment by Fleid** [comment]
ASA only supports authentication via key to Function at the moment. We are considering adding other options, a feedback item was created here: https://feedback.azure.com/d365community/idea/9228d53d-b925-ec11-b6e6-000d3a4f0f1c
