### ISSUE TITLE
Writing into CosmosDb with a number PartitionKey value converts to string

### ISSUE THREAD

**Issue by adamvanaken** [Azure/azure-stream-analytics#86]
I have a pretty basic pass-through from EventHubs to a CosmosDB collection. However the values being written into the collection's partition key property are being cast to string seemingly somewhere between ASA and Cosmos. I have tried casting to bigint, but that did nothing. Note the non-partition property correctly has the number value:

	SELECT
		ProductId,
		FeatureString,
		CountryIso,
		UltimateId, // pass through, partition key prop
		UltimateId as UltimateIdInt, // pass through, NOT partition key prop
		MachineName,
		UserName
	INTO 
		ConcurrentMachineDb
	FROM 
		Input PARTITION BY PartitionId
	WHERE 
		IsBadData = 0
	GROUP BY 
		TUMBLINGWINDOW(second, 2), 
		PartitionId,
		MachineName, 
		UserName, 
		ImsId, 
                PolicyFileId,
                SecurableId,
		UltimateId, 
		CountryIso

This is the downloaded output from testing the query in the azure portal to show that we are indeed getting and writing numbers: 
![image](https://user-images.githubusercontent.com/5086278/92269837-f75edc80-eeb2-11ea-824a-5cdfa4c4292f.png)

However this is the record as shown in Cosmos, where the `UltimateId` property is now a string, but the non-partition key prop is still a number:
![image](https://user-images.githubusercontent.com/5086278/92269787-df875880-eeb2-11ea-9f53-024e264cde9f.png)

Proof of our partition key setup in Cosmos:
![image](https://user-images.githubusercontent.com/5086278/92270436-0abe7780-eeb4-11ea-97bb-bc4174744931.png)

What's going on here?

**Comment by Fleid** [comment]
Sorry for the late answer. This was a behavior of our Cosmos DB output adapter that has been fixed end of 2020.
It should have been behaving property for some time now.
