### ISSUE TITLE
Cannot use "timestamp" column when saving to table storage

### ISSUE THREAD

**Issue by bGridSven** [Azure/azure-stream-analytics#87]
When saving to the table storage from Stream Analytics I cannot use the column "timestamp", not to be confused with the automatically generated column "Timestamp".

When using azure functions to save to the table storage I am allowed to use the "timestamp" column, but when using Stream Analytics the values get filled with null.

Here an example where the top row is saved using Stream Analytics and the bottom row is saved using Azure Functions displaying that it is possible to use the column, but that it doesn't work for stream analytics. To make sure that the timestamp exists the RowKey of the first column contains the (unix)timestamp.

![image](https://user-images.githubusercontent.com/50664929/94675533-2afa1e80-031a-11eb-8b49-d004922c7273.png)

**Comment by sidramadoss** [comment]
There is a limitation today in Stream Analytics where you cannot differentiate 2 columns with the same name (even with different casing). We have a work item in our backlog to address this but unfortunately cannot provide an ETA.
