### ISSUE TITLE
Namespace sb://xxxxxxxx.azure-devices.net:80/ does not exist. while testing IoT Hub input in Stream Analytics Job

### ISSUE THREAD

**Issue by codekat9** [Azure/azure-stream-analytics#88]
Hello,

I have an iot hub. I have created a Stream Analytics Job to send the data from hub to an Azure SQL DB. I am trying to define an input to get the data from the iot hub. I have defined the default settings. When I try to test the connection, I get the issue  Namespace sb://xxxxxxxx.azure-devices.net:80/ does not exist. I have tried many things like creating a separate consumer group but it doesn't work. Can someone help me in finding out what might be the issue?

Thanks.

**Comment by sidramadoss** [comment]
@codekat9 - is your IoT Hub input in a VNET or behind a firewall?

**Comment by ismaan1998** [comment]
Yes , I am facing the same issue, and my IoT Hub is behind the vnet, @sidramadoss any idea how to solve this issue?

**Comment by Fleid** [comment]
@ismaan1998 is your ASA job running in a cluster? https://techcommunity.microsoft.com/t5/analytics-on-azure/introducing-stream-analytics-clusters-with-vnet-support/ba-p/1696120

This is how Stream Analytics supports VNET integration.

**Comment by sidramadoss** [comment]
@ismaan1998 - here is the link to the doc that shows how to configure private endpoints from ASA cluster to your IoT hub. https://docs.microsoft.com/en-us/azure/stream-analytics/private-endpoints

Without using ASA clusters, there is no option to use private endpoints to connect ASA jobs to IoT Hub.

**Comment by ismaan1998** [comment]
Thanks @sidramadoss , I'll have a look on this and i think we can close this issue as well
