### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by berida10** [Azure/azure-stream-analytics#9]
Hi, I have tried to run the Twitter Client first just from downloading the zip folder from here: https://azure.microsoft.com/nb-no/documentation/articles/stream-analytics-twitter-sentiment-analysis-trends/
And then providing the information to the config file- saving. 
The application just closes. I also downloaded the project from here, and ran it in VS. There it throws an exception, An exception of type 'System.AggregateException' occurred in mscorlib.dll but was not handled in user code. The remote server returned an error: (401) Unauthorized.

Any idea what is causing this error? I would guess it's the event hub, but I don't know why. Would be greatful of any help :) 

Ida

**Comment by dprabhath** [comment]
Hi, Any solution for above issue?

**Comment by flomader** [comment]
It's not an Event Hub problem. It's a connection problem to the Twitter API.
Double check your keys in the App.config. I ran into the same problem because I made a mistake copying the keys into the App.config and had a leading whitespace in one of the keys.

**Comment by jeffstokes72** [comment]
Good call @flomader this is a common occurrence and we're looking at changing our demos to accommodate the likelihood of this issue (field checking logic in a UI instead maybe)

**Comment by LineOfCode** [comment]
It looks like the Keys weren't url encoded. I have put in a pull request. Please note there is new functionality in there as well and the configuration has changed a little.  Once we review we will push.

**Comment by LineOfCode** [comment]
![i16 cimgpsh_orig](https://cloud.githubusercontent.com/assets/8649063/21451367/adbd729a-c8cc-11e6-94eb-ae38cbd4c23b.png)

GUI coming soon.

**Comment by apoo777** [comment]
Hi, I still receive the same exception i.e. The remote server returned an error: (401) Unauthorized for the [TwitterClient](https://github.com/Azure/azure-stream-analytics/tree/master/DataGenerators/TwitterClient) and the config file details have been double checked. Could there be any other reason for this? The resouce URL https://stream.twitter.com/1.1/statuses/filter.json?track=Azure exists or is it deprecated?

Thanks in advance!

**Comment by Fleid** [comment]
Closing stale issues
