### ISSUE TITLE
No indication, when delivering to a disabled event hub

### ISSUE THREAD

**Issue by asindl** [Azure/azure-stream-analytics#93]
When delivering to an event hub, that is "disabled", the stream analytics job continuously ran, but after some seconds didn't consume any incoming messages anymore. There was no indication or error message, the job just ran on, with not processing any data.
It took me some hours to find out, that a colleague had set the event hub to "disabled". By the behavior of the job, I couldn't tell, if there was any issue at all, if it was the incoming stream or the output stream.

**Comment by Fleid** [comment]
I would have expected the job to get into a [degraded](https://docs.microsoft.com/en-us/azure/stream-analytics/job-states) status.

Anyway you have to set up [monitoring and alerts](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-set-up-alerts) on your jobs, so you are made aware these sorts of issues. Let's say it's your input EG that gets somehow disabled, that will not trigger any issue on the ASA side, but if you have set up alerts you will be notified.
