### ISSUE TITLE
Difference between EventEnqueued and EventProcessed is more than 1 hour.

### ISSUE THREAD

**Issue by ismaan1998** [Azure/azure-stream-analytics#94]
We've a stream analytics and we've selected IoT Hub as input. 
Selected IoT Hub is receiving 3600 telemetry messages per hour. 

On Stream analytics, It is taking more than a hour to process the messages received from IoT Hub. 
 
![image](https://user-images.githubusercontent.com/30122168/119789468-b56a4080-bef0-11eb-918c-81ece4f5394a.png)

Is there any way that we can make it fast?

**Comment by sidramadoss** [comment]
@ismaan1998 - did you try to follow the troubleshooting guidance mentioned here: https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-troubleshoot-output

There are multiple reasons why this could happen. Please open a support ticket if following instructions in doc doesn't help - this will ensure you get the right answers.

**Comment by ismaan1998** [comment]
Hi @sidramadoss , It was some problem related to Power BI, so stream analytics wasn't able to send the data to defined output, that's why the processed time was late.


Thanks for helping.

Closing this issue
