### ISSUE TITLE
Multiple queries in a single ASA job

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-stream-analytics#98]
I have a use case where the customer can select the alert parameters from the web UI and there value too. Now, I want create the query for each alert using the parameters and value provided by the customer.

So lets say n customer create N alert queries [all are different queries with different values and fields etc.]. Now how can I support this in ASA.

1) Do I need to make N ASA jobs for this? 
2) Can I some create one job and that job runs all the N queries on each input event? I could not find anything regarding this feasibility on the Internet

Any help is appreciated.

**Comment by Fleid** [comment]
This [article](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-threshold-based-rules) describes how to implement dynamic rules in a single job. The gist of it is that you store rules definition in a SQL table or blob file, and use that in your query via a reference table.

But that means that all your rules (alert queries) follow the same template and time resolution (window duration).

If you need more configurability, then you will have to generate and deploy jobs dynamically using the [C# SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.streamanalytics?view=azure-dotnet) or the [REST API](https://docs.microsoft.com/en-us/rest/api/streamanalytics/). Note that this is the easy part, the more interesting challenge will be to generate queries dynamically. We have large scale customers that have adopted that pattern, it's an investment but it works well.

That second approach is N jobs for N alert queries.
The first one is 1 job (1 ASA query) for N alert queries.

We don't support N independent queries in a single job, but a query can process many independent pipelines. The issue you will have here is that you won't be able to scale (we scale primarily per partition in a single data flow, so independent data flows will prevent that), and everytime you change the query (for a new rule) then you will need to restart the job and impact every rule.

I hope that helps, let me know if you have follow-ups.

**Comment by amit12cool** [comment]
I'm already creating queries in code so that difficult part is already done.

What I understand from your answer is the template approach will not work for my use case as my data and fields for alert rules is dynamic and cannot live in a template reference data.

So I have to create a separate job for each alert query i.e. n queries and n jobs. Is it correct understanding?

If so, then what is the maximum number of jobs I can create in ASA?

**Comment by Fleid** [comment]
> What I understand from your answer is the template approach will not work for my use case as my data and fields for alert rules is dynamic and cannot live in a template reference data.

It depends of what exactly you consider dynamic for data and fields. With [GetRecordPropertyValues](https://docs.microsoft.com/en-us/stream-analytics-query/getrecordpropertyvalue-azure-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json) you can access a field dynamically. So you can make the field name a parameter of the rule definition. Same with the threshold, obviously, but also for the operator to be applied (GREATER, LESSER...).

But if you're aggregating the incoming stream and need to dynamically pick the type of aggregation (AVG. SUM...) and/or the time window (and its duration), then you can't use that approach.

> So I have to create a separate job for each alert query i.e. n queries and n jobs. Is it correct understanding?

If the above is true, then you do need to create one ASA job per alert query. 

Unless you manage to regroup alert query types per pattern, and use the template approach for each of these patterns. So one job for all alert queries that are tumbling windows, and you use [multiple windows](https://docs.microsoft.com/en-us/stream-analytics-query/windows-azure-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json) to offer only a choice of predefined durations. Another job for all hopping windows, etc... You can offer a choice of aggregations (AVG, SUM...) via a CASE.

> If so, then what is the maximum number of jobs I can create in ASA?

You can have [1500 jobs per region in a subscription](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#stream-analytics-limits). There is also a cap in terms of SU per region, at 500, but it can be raised.

> Also I'm not abe to understand what is meant by a query can process many independent pipelines. Could you please elaborate with an example?

You can create a job that at the same time:
- reads from Input IA, compute query QA and output to OA
- reads from Input IB, compute query QB and output to OB
- reads from Input IC, compute query QC and output to OC 

So something like:
```SQL
SELECT * INTO OA FROM IA
SELECT * INTO OB FROM IB
SELECT * INTO OC FROM IC
```

Each of these data flow, A, B and C, are here completely independent. This is not very scalable. The best we can do is distribute each subquery onto its own node, but that's all. It's best to avoid this approach if you expect to scale at any point.

**Comment by amit12cool** [comment]
`It depends of what exactly you consider dynamic for data and fields. With GetRecordPropertyValues you can access a field dynamically. So you can make the field name a parameter of the rule definition. Same with the threshold, obviously, but also for the operator to be applied (GREATER, LESSER...).`

Dynamic for me is that the field itself will change. For example, Customer 1 creates query like this `SELECT abcd as efgh FROM input INTO output` and another customer creates a query like this `SELECT ijk as lmn FROM input INTO output`. So both customers have varying field names and that can happen with N customers. Still Im thinking how can I support this use case with reference data.

**Comment by Fleid** [comment]
GetRecordPropertyValues will allow you to grab that field dynamically.

You have you reference table/file that lists the query rules with a schema like : FieldName, Operator, Threshold, ScopeKey.
ScopeKey can be deviceId, customerId, whatever defines the scope of that rule.

Then in the query you left join over it from the stream:

```SQL
SELECT
        S.*
FROM MyStream S
LEFT JOIN MyRules R ON S.ScopeKey = R.ScopeKey
WHERE
        (Operator= 'GREATEROREQUAL' AND GetRecordPropertyValue(S.MyRecord,R.FieldName) >=  R.Threshold) OR
        (Operator= 'EQUALORLESS' AND GetRecordPropertyValue(S.MyRecord,R.FieldName) <=  R.Threshold) 
```

Note that here I suppose your stream schema is something like:
```JSON
{
    "ScopeKey" : "978648", 
    "MyRecord" :
    {
        "Temperature" : 80,
        "Humidity" : 70,
        "CustomSensor01" : 5,
        "CustomSensor02" : 99
    }
}
```
And an exemple of rule that applies would be:
|FieldName|Operator|Threshold|ScopeKey|
|-|-|-|-|
|Temperature|GREATEROREQUAL|75|978648|

**Comment by amit12cool** [comment]
Is it possible to have more than one query rule in the reference data file? Because in my use case there can be any number of rules with any number of operator and with any threshold value for the field? If so, will all the rules be applied to each of the event bulg your approach above.?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amit12cool** [comment]
@Fleid  Any update on above?

**Comment by Fleid** [comment]
> Is it possible to have more than one query rule in the reference data file? Because in my use case there can be any number of rules with any number of operator and with any threshold value for the field? If so, will all the rules be applied to each of the event as per your  approach above.?

Yes, that's what the pattern is for.

Let's say you have 2 rules for deviceA and 3 rules for deviceB (so 5 rules aka 5 rows total in your reference dataset). Those 2 devices stream 10 data points each per second.

The join described above will process 50 data points per second (2*10 + 3*10). 

The rules will be applied to the scope you define. It was scopeKey in my initial join statement, just above it's the device name. You will have to decide which scope applies, make it part of the rule definition, and use it as the join key in the stream.

> I'm also wondering how can I everytime change the threshold values from code in the reference data? I mean the reference data is totally dynamic in my use case and it will.be always derived from my code that is when customer creates the rule in the UI.

The reference dataset will need to be made refreshable. See [the doc](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-use-reference-data) on how. Note that the minimal refresh delay is 1 minute, so it will take a minimum of 1 minute between when a rule is created/updated and when it's applied.

> And how the select fields? Does S.* means anything can be there in front of Select? If not, how will that be made dynamic as I don't have a static fields names to select it can be any field.

You can grab a field dynamically via GetRecordPropertyValue and give it name the destination is expecting:

```SQL
SELECT
        R.FieldName AS AlertField,
        R.Operator AS AlertOperator,
        R.Threshold AS AlertThreshold,
        GetRecordPropertyValue(S.MyRecord,R.FieldName) AS CurrentValue
FROM MyStream S
LEFT JOIN MyRules R ON S.ScopeKey = R.ScopeKey
WHERE
        (Operator= 'GREATEROREQUAL' AND GetRecordPropertyValue(S.MyRecord,R.FieldName) >=  R.Threshold) OR
        (Operator= 'EQUALORLESS' AND GetRecordPropertyValue(S.MyRecord,R.FieldName) <=  R.Threshold) 
```

**Comment by amit12cool** [comment]
Any limit on the reference data set rows? Can I add as many as I can?

**Comment by Fleid** [comment]
See [that part of the doc](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-use-reference-data#size-limitation) for the size limitation.

**Comment by amit12cool** [comment]
> so 5 rules aka 5 rows total in your reference dataset

How are they specified in the JSON file? Is it an array of objects?

**Comment by amit12cool** [comment]
@Fleid I was able to create the query and almost on the verge of finishing it. But one thing that is a type of blocker for me is to support array property values in reference data and use them in the job query, Any example would help?

**Comment by Fleid** [comment]
Second half of [this one](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-parsing-json) should help. Let me know if you're stuck ;)

**Comment by amit12cool** [comment]
I already looked at it. My query is like property = value1 OR property = value2 OR property = value3.  value1, value 2, value3 are array values of property in reference data.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amit12cool** [comment]
I have an array property in reference data and not in the event stream. The above example seems to be working on array property coming in event stream.

**Comment by Fleid** [comment]
Closing the issue, please re-open if need be.

**Comment by amit12cool** [comment]
@Fleid I was able to create the queries using 2 reference data file located in blob storage. But somehow ASA job is not loading the second reference data file from blob as checked in my ASA job execution diagnostic logs. Is it supported by ASA to load more than 1 reference data files.? Note:- I have the same timestamp name for both reference files in blob.

**Comment by sidramadoss** [comment]
@amit12cool - yes, ASA supports using multiple reference data input sources in the same job. It sounds like the second reference data input might not be configured correctly (serialization type, location etc). I recommend using live data testing capability in VSCode to troubleshoot your problem: https://docs.microsoft.com/en-us/azure/stream-analytics/visual-studio-code-local-run-live-input 

If you are unable to figure out what is going on, please create a support ticket to get this resolved.

**Comment by amit12cool** [comment]
Ok. I will try the VScode solution once. On the other hand, I did doubly check the configuration for both inputs is correct in job as I see the diagnostic logs for the Receive events string but it loads only one of the files. That too sometimes it loads first ref file and sometimes the second one.

Right now, my folder structure on blob is as below

`rules/07-11-2021/15-38/rules1.json`
`rules/07-11-2021/15-38/rules2.json`

Is above correctly structured? Or I need to put files in different folders?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sidramadoss** [comment]
Looks ok but you can also try creating a different folder structure for the second ref data and seeing that helps.

**Comment by amit12cool** [comment]
Yes, I did that but that also didn't worked for me and it loaded one of the reference data files only

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sidramadoss** [comment]
Please create a support ticket so that we can collect more details of the job etc and the team can help you out.

**Comment by amit12cool** [comment]
Ok.. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amit12cool** [comment]
@sidramadoss @Fleid I tried the VScode solution too with different path for second reference data file. Still the issue persist. Check attached image which only shows that my one  of the reference data is loaded.
![Screenshot 2021-11-09 184722](https://user-images.githubusercontent.com/6692132/140931147-accbb1b7-10b7-4dd7-bc4f-16d38b54904d.png)
Note:- I don't have subscription for tech support if possible please provide the solution here.

**Comment by sidramadoss** [comment]
@amit12cool can you please email askasa [at] microsoft [dot] com sharing your sample streaming input, ref data input and query?

**Comment by amit12cool** [comment]
@sidramadoss I have sent a email few days back, still waiting for the response.

**Comment by amit12cool** [comment]
@sidramadoss @Fleid any chance you got to look at this. It's urgent for me
